name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: |
        pip install -r requirements.txt
        pyinstaller --onefile --windowed --name BatchImageCrop --collect-all ttkbootstrap --collect-all tkinterdnd2 --hidden-import PIL._tkinter_finder --hidden-import tkinterdnd2 BatchImageCrop.py

    - uses: actions/upload-artifact@v4
      with:
        name: BatchImageCrop
        path: dist/BatchImageCrop.exe
